#!/usr/bin/env bash
php mage/install.php \
--license_agreement_accepted "yes" \
--locale "en_US" \
--timezone "Europe/Riga" \
--default_currency "USD" \
--db_host "localhost" \
--db_name "mage_api_pp" \
--db_user "mage_api_pp" \
--db_pass "..." \
--url "http://paypal_api.local.net/" \
--use_rewrites "no" \
--use_secure "no" \
--secure_base_url "http://paypal_api.local.net/" \
--use_secure_admin "no" \
--admin_lastname "Admin" \
--admin_firstname "Test" \
--admin_email "admin@email.com" \
--admin_username "admin" \
--admin_password "..."